# Generated by Django 2.2.10 on 2020-03-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200311_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
