# Generated by Django 2.2.10 on 2020-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoice_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_terms',
            field=models.TextField(blank=True, default='NET 30 Days. Finance Charge of 1.5% will be             made on unpaid balances after 30 days.'),
        ),
    ]
