
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  lint:
    working_directory: ~/django-invoices
    docker:
      - image: circleci/python:3.6.8-browsers
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgres container.
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_DB: "db"
          DATABASE_URL: "postgres://postgres@postgres:5432/db"
          DEBUG: True
    steps:
      - checkout
      # - setup_remote_docker # https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Install Python dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.in
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{checksum "requirements.in"}}

      - run:
          name: Run linter checks
          command: |
            . venv/bin/activate
            make lint

  test-django-invoices:
    working_directory: ~/django-invoices
    machine: true

    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            docker-compose run web coverage run manage.py test -v 3

      - run:
          name: Calculate Coverage
          command: |
            docker-compose run web coverage report
            docker-compose run web coverage html
            docker-compose run web coverage xml
            docker-compose run web codecov -t $CODECOV_TOKEN

      - run:
          name: "Print branch info"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Download and install Divio CLI tool"
          command: |
            docker-compose run web divio login $DIVIO_ACCOUNT
            # docker-compose run web divio --help
            # docker-compose run web divio project deploy --remote-id <website id>
            docker-compose run web divio project deploy-log --remote-id $DJANGO_INVOICES_ID
      - codecov/upload:
          file: coverage.xml
      - store_artifacts:
          path: htmlcov


workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-django-invoices:
          filters:
            branches:
              only: develop
